In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import re
import string

In [2]:
data_fake = pd.read_csv('fake.csv')
data_true = pd.read_csv('true.csv')

C:\Users\yasas\AppData\Local\Temp\ipykernel_1156\1257269473.py:1: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128) have mixed types. Specify dtype option on import or set low_memory=False.
  data_fake = pd.read_csv('fake.csv')

In [4]:
data_fake.head()

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128
0,Donald Trump Sends Out Embarrassing New Year’s...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Drunk Bragging Trump Staffer Started Russian C...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sheriff David Clarke Becomes An Internet Joke ...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Trump Is So Obsessed He Even Has Obama’s Name ...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pope Francis Just Called Out Donald Trump Duri...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [6]:
data_fake["class"] = 0
data_true["class"] = 1

In [7]:
data_fake.shape,data_true.shape

((23500, 130), (21417, 5))

In [8]:
data_fake_manual_testing = data_fake.tail(10)
for i in range(23480,23470,-1):
    data_fake.drop([i],axis=0,inplace = True)

data_true_manual_testing = data_true.tail(10)
for i in range(21416,21406,-1):
    data_true.drop([i],axis=0,inplace = True)

In [9]:
data_fake.shape,data_true.shape

((23490, 130), (21407, 5))

In [10]:
data_fake_manual_testing.head(10)

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,class
23490,Seven Iranians freed in the prisoner swap have...,"21st Century Wire says This week, the historic...",Middle-east,"January 20, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
23491,#Hashtag Hell & The Fake Left,By Dady Chery and Gilbert MercierAll writers ...,Middle-east,"January 19, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
23492,Astroturfing: Journalist Reveals Brainwashing ...,Vic Bishop Waking TimesOur reality is carefull...,Middle-east,"January 19, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
23493,The New American Century: An Era of Fraud,Paul Craig RobertsIn the last years of the 20t...,Middle-east,"January 19, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
23494,Hillary Clinton: ‘Israel First’ (and no peace ...,Robert Fantina CounterpunchAlthough the United...,Middle-east,"January 18, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
23495,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
23496,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
23497,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
23498,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
23499,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [11]:
data_true_manual_testing.head(10)

,title,text,subject,date,class
21407,"Mata Pires, owner of embattled Brazil builder ...","SAO PAULO (Reuters) - Cesar Mata Pires, the ow...",worldnews,"August 22, 2017",1
21408,"U.S., North Korea clash at U.N. forum over nuc...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21409,"U.S., North Korea clash at U.N. arms forum on ...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21410,Headless torso could belong to submarine journ...,COPENHAGEN (Reuters) - Danish police said on T...,worldnews,"August 22, 2017",1
21411,North Korea shipments to Syria chemical arms a...,UNITED NATIONS (Reuters) - Two North Korean sh...,worldnews,"August 21, 2017",1
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [12]:
data_merge = pd.concat([data_fake, data_true],axis = 0)
data_merge.head(10)

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,class
0,Donald Trump Sends Out Embarrassing New Year’s...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,Drunk Bragging Trump Staffer Started Russian C...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,Sheriff David Clarke Becomes An Internet Joke ...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,Trump Is So Obsessed He Even Has Obama’s Name ...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,Pope Francis Just Called Out Donald Trump Duri...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5,Racist Alabama Cops Brutalize Black Boy While ...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
9,WATCH: Brand-New Pro-Trump Ad Features So Much...,Just when you might have thought we d get a br...,News,"December 21, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [13]:
data_merge.columns

Index(['title', 'text', 'subject', 'date', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'class'],
      dtype='object', length=130)

In [14]:
data = data_merge.drop(['title','subject','date'],axis = 1)

In [15]:
data.isnull().sum()

text              632
Unnamed: 4      44878
Unnamed: 5      44879
Unnamed: 6      44879
Unnamed: 7      44879
                ...
Unnamed: 125    44895
Unnamed: 126    44895
Unnamed: 127    44895
Unnamed: 128    44895
class               0
Length: 127, dtype: int64

In [16]:
data = data.sample(frac = 1)
# shuffles the rows of the DataFrame data
# frac=1 indicates that it selects all rows, essentially shuffling the entire DataFrame. This operation is commonly used to randomize the order of rows in a dataset.

In [17]:
data.head()

,text,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,class
1620,"In an unreal feat, Trump managed to have two h...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
12636,CAIRO/GAZA (Reuters) - Palestinian President M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
7920,"In 2014, Tennessee lawmakers passed a bill whi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5942,(Reuters) - Highlights of the day for U.S. Pre...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2734,WASHINGTON (Reuters) - The U.S. Supreme Court ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [18]:
data.reset_index(inplace=True)
data.drop(['index'],axis=1,inplace=True)

# inplace=True modifies the DataFrame in place, meaning it doesn't return a new DataFrame but instead modifies the existing one.
# adds a new column named "index" containing the old index values and resets the index to the default integer index (0, 1, 2, ...)
# drop() function is used to remove columns or rows from a DataFrame. 
# axis=1 indicates that it's a column operation.

In [19]:
data.columns

Index(['text', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'class'],
      dtype='object', length=127)

In [20]:
data.head()

,text,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,class
0,"In an unreal feat, Trump managed to have two h...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,CAIRO/GAZA (Reuters) - Palestinian President M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,"In 2014, Tennessee lawmakers passed a bill whi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,(Reuters) - Highlights of the day for U.S. Pre...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,WASHINGTON (Reuters) - The U.S. Supreme Court ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [ ]:
import re

def wordopt(text):
    if isinstance(text, str):
        text = text.lower()
        text = re.sub('\[.*?\]','',text)
        text = re.sub("\\W"," ",text)
        text = re.sub('https?://\S+|www\.\S+', '', text)
        text = re.sub('<.*?>+', '', text)
        text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
        text = re.sub('\n', '', text)
        text = re.sub('\w*\d\w*', '', text)
    else:
        text = str(text)  # Convert non-string values to empty strings
    return text

In [1]:
data['text'] = data['text'].apply(wordopt)

NameError: name 'data' is not defined

In [23]:
x=data['text']
y=data['class']

In [24]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
vector = TfidfVectorizer()
tf_train = vector.fit_transform(x_train)
tf_test = vector.transform(x_test)

In [26]:
print(tf_train)

  (0, 20870)	0.01971501481864409
  (0, 11939)	0.012728416112801236
  (0, 27008)	0.02108881924902331
  (0, 69762)	0.01865269818384025
  (0, 78527)	0.021544870854129778
  (0, 72294)	0.022097683749805103
  (0, 61751)	0.019669248360474595
  (0, 83084)	0.02797140890597958
  (0, 19449)	0.021464047117513874
  (0, 23514)	0.034577984270958664
  (0, 68403)	0.029144391032284694
  (0, 20816)	0.029674776710915746
  (0, 65865)	0.03067305817570853
  (0, 76042)	0.01211280757486681
  (0, 7595)	0.027755605277001667
  (0, 16762)	0.03200810483679035
  (0, 28964)	0.02674168302176561
  (0, 73368)	0.02056380381908083
  (0, 27944)	0.03468042452127198
  (0, 10489)	0.027325419561767678
  (0, 30217)	0.019777599062729242
  (0, 54866)	0.016557414463023078
  (0, 6925)	0.02387789516604486
  (0, 83634)	0.009860809081214051
  (0, 91878)	0.030488785642084525
  :	:
  (33671, 16694)	0.13762988454157093
  (33671, 86337)	0.08164121947227519
  (33671, 60162)	0.19299624177578395
  (33671, 65202)	0.2362879234310944
  (33671, 91621)	0.056581946678603195
  (33671, 6330)	0.30409772734347723
  (33671, 66613)	0.29934864554766044
  (33671, 53642)	0.13130042323328625
  (33671, 45439)	0.24398557009972496
  (33671, 57952)	0.1976708675375403
  (33671, 65151)	0.048468435265262975
  (33671, 11939)	0.07392608897379659
  (33671, 7219)	0.0411201161882949
  (33671, 29956)	0.03477717484068149
  (33671, 56900)	0.06029114916890862
  (33671, 41353)	0.037338797289749925
  (33671, 3092)	0.042440032532647644
  (33671, 59002)	0.0313146436451659
  (33671, 3187)	0.06322676636791247
  (33671, 72588)	0.038681383932936776
  (33671, 83420)	0.06064851826153019
  (33671, 84545)	0.09299861746642304
  (33671, 59406)	0.1282021180307539
  (33671, 11618)	0.03938247637724874
  (33671, 70337)	0.05093627940255729

In [27]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(tf_train, y_train)

LogisticRegression()

In [28]:
y.pred = LR.predict(tf_test)

In [ ]:
accuracy= LR.score(tf_test, y_test)
from sklearn.metrics import precision_score, recall_score, f1_score
import matplotlib.pyplot as plt
import numpy as np


# Assuming LR is your logistic regression model
# Assuming tf_test is your test data after TF-IDF transformation
# Assuming y_test is your test labels

# Get predictions from your LR model
predictions = LR.predict(tf_test)

# Calculate precision, recall, and F1-score
precision = precision_score(y_test, predictions)
recall = recall_score(y_test, predictions)
f1 = f1_score(y_test, predictions)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

labels = ['Accuracy', 'Precision', 'F1 Score', 'Recall']

# Scores
scores = [accuracy, precision, f1, recall]

# Plotting
plt.figure(figsize=(8, 6))
plt.bar(labels, scores, color=['blue', 'green', 'orange', 'red'])
plt.title('Performance Metrics for Logistic Regression')
plt.xlabel('Metrics')
plt.ylabel('Scores')
plt.ylim(0, 1)  # Limit y-axis from 0 to 1
plt.show()

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset (replace 'data.csv' with your actual dataset)
df = pd.read_csv('fake.csv')

# Compute correlation matrix
correlation_matrix = df.corr()

# Visualize correlation matrix as a heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix')
plt.show()

In [30]:
def output_lable(n):
    if n==0:
        return "Fake News"
    elif n==1:
        return "Not A Fake News"
def manual_testing(news):
    testing_news = {"text":[news]}
    new_def_test = pd.DataFrame(testing_news)
    new_def_test['text'] = new_def_test["text"].apply(wordopt)
    new_x_test = new_def_test['text']
    new_xv_test = vector.transform(new_x_test)
    y.pred = LR.predict(new_xv_test)
    return print("\n\nLR Prediction : {} ".format(output_lable(y.pred[0])))

# Input: It takes a single news article (news) as input.

# Create DataFrame: It creates a DataFrame new_def_test containing the input news article. This DataFrame has a single column named "text" containing the news article.

# Text Preprocessing: It preprocesses the text data in the "text" column of the DataFrame using the function wordopt().

# Feature Extraction: It transforms the preprocessed text data into numerical feature vectors using the same vectorizer (vector) that was used during training.

#Prediction: It uses a trained logistic regression model (LR) to predict the label (real or fake) for the input news article.

#Output: It prints the prediction result using the function output_lable(), which likely converts the predicted label into a human-readable format.

In [ ]:
news = str(input())
manual_testing(news)

In [ ]:
import pickle
import sys
filename = 'finalized_model.pkl'
pickle.dump(LR,open(filename,'wb'))

In [ ]:
filename = 'vectorizer.pkl'
pickle.dump(vector,open(filename,'wb'))

In [ ]:
pip install seaborn

In [ ]:


import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset (replace 'data.csv' with your actual dataset)
df = pd.read_csv('fake.csv')

# Compute correlation matrix
correlation_matrix = df.corr()

# Visualize correlation matrix as a heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix')
plt.show()

In [ ]:
model.predict(X_train)